### ISSUE TITLE
Inspired Teaching (SC = 3064) - enrollment by grade

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#72] opened 2015-01-08 20:40 UTC
Accepts enrollment in all of these grades, so no text should appear at all.

**Comment by cmgiven** [comment] 2015-01-08 21:12
Assigning to Ben. This needs to be updated in the data files.

**Comment by benjaminrobinson** [comment] 2015-01-09 17:16
A little confused on where to look here to make the fix...

**Comment by cmgiven** [comment] 2015-01-09 17:18
This is set in the school overview files. There's an array that indicates which grades accept enrollment, and if it differs from the grades offered, the text gets displayed.

**Comment by benjaminrobinson** [comment] 2015-01-09 17:27
Thanks for the clarification on that, Chris.  Do you know where the school overview files are located? I feel like I've never actually seen the files feeding that part of the Equity Report.

**Comment by cmgiven** [comment] 2015-01-09 17:39
I do not, unfortunately. Note that these are not specific to the Equity Report. They are not in the v2 repo, and have always been shared via email with us.


—

**Comment by benjaminrobinson** [comment] 2015-01-09 17:41
Thanks, Chris!  I'll find the source of school overview files and make the change...Down the line, if we want to add those files to the GitHub repo at some point to make life easier for us all, I am open to it.

**Comment by cmgiven** [comment] 2015-01-09 17:43
So are we!


—

**Comment by cmgiven** [comment] 2015-01-09 18:07
@mepps and @psteininger: Can you help us determine why PK3-KG are appearing as "Does Not Accept Enrollment." Here's the overview file:

https://github.com/socialdriver/learndc-data/blob/master/converted/school/3064/overview.json

Here's the Equity Report:

http://www.stage.learndc.org/schoolprofiles/view?s=3064#equityreport

Ben is aware that Grade 7 is present in one array but not the other, and is looking into the issue.

Again, per Gwen's initial note, the expected result is that as all grades accept enrollment, the labels should not be present on this school's Equity Report.

**Comment by benjaminrobinson** [comment] 2015-01-13 18:00
Is this a duplicate of #77 ?

**Comment by cmgiven** [comment] 2015-01-14 18:13
Yes, this is a dupe.

**Closed by cmgiven** 2015-01-14 18:13 UTC
Labels: Parking Lot
