### ISSUE TITLE
Front-end: Errant min-width rule mis-sizes small values

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#94] opened 2015-01-26 03:27 UTC
![screenshot 2015-01-25 22 26 26](https://cloud.githubusercontent.com/assets/7264714/5895044/65a419f2-a4e1-11e4-8ccc-09ddbb5a5a7c.png)

**Comment by gwenrr** [comment] 2015-01-26 14:05
It seems fine now - but if someone could tell me why they think this was the case (even if it's as simple as you need to reset your browser or clear your cache), I would appreciate it. Then I can close it. Thanks.

**Comment by gwenrr** [comment] 2015-01-26 14:05
Oops - closed accidentally.

**Comment by cmgiven** [comment] 2015-01-26 14:13
I can reproduce in Safari. Note that the issue is actually with the school value (the purple bar) being too big, not the yellow line being too small.

**Comment by cmgiven** [comment] 2015-01-26 14:14
Found it. There's a min-width rule on the bar. This needs to be removed.

```min-width: 45px !important;```

**Comment by gwenrr** [comment] 2015-01-26 14:16
Thank you!

**Comment by mepps** [comment] 2015-01-26 14:25
Fixed on prod. 
![screen shot 2015-01-26 at 9 25 02 am](https://cloud.githubusercontent.com/assets/4406809/5901060/3bb7a7d8-a53d-11e4-96d2-0a499a696841.png)

**Closed** 2015-01-26 14:25 UTC
