### ISSUE TITLE
teacher data = labeling of state numbers missing on school exhibits

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#131] opened 2015-04-06 17:49 UTC
![screenshot 2015-04-06 13 43 43](https://cloud.githubusercontent.com/assets/7264714/7008777/b1997118-dc63-11e4-80bc-ff3374d38f9a.png)

**Comment by mepps** [comment] 2015-04-06 17:56
![screen shot 2015-04-06 at 1 55 01 pm](https://cloud.githubusercontent.com/assets/4406809/7008924/9ac0d778-dc64-11e4-8967-8042a246bb4e.png)

Before we included the state data, leaving off the section headings for schools was intentional, because they don't have the same category breakdowns. Here's my suggestion though for consistency. (We can't use the same keys as in other places because of the data changes between the school and the lea hqt_classes exhibits)

**Comment by mepps** [comment] 2015-04-06 17:57
We could also say "This School", or another label of your suggestion.

**Comment by gwenrr** [comment] 2015-04-06 18:03
"This School" and "This LEA" would be great - not "all school"

Could this not be the column heading in column #2?

**Comment by cmgiven** [comment] 2015-04-06 18:04
Yes, we've used "This School"/"This LEA" before.

**Comment by mepps** [comment] 2015-04-06 18:14
![screen shot 2015-04-06 at 2 13 20 pm](https://cloud.githubusercontent.com/assets/4406809/7009272/1dfd8b2a-dc67-11e4-8715-74b82b186624.png)

Here it is with "This School".

**Comment by cmgiven** [comment] 2015-04-06 18:15
Possible to have in the column above the numbers, so that it parallels State?

**Comment by mepps** [comment] 2015-04-06 18:16
Let's discuss this during the call.

**Comment by cmgiven** [comment] 2015-04-06 18:17
Oh, and also "State" should be "DC" consistent with elsewhere. You know, 'cuz it's not *technically*...

**Comment by mepps** [comment] 2015-04-06 18:24
![screen shot 2015-04-06 at 2 22 57 pm](https://cloud.githubusercontent.com/assets/4406809/7009464/72e6d852-dc68-11e4-9773-2b991b137e94.png)

Here's what it would look like with "This School" in that column. We would still need  a section header for that data or just leave it blank.

**Comment by gwenrr** [comment] 2015-04-06 18:31
Looks better! I think leave it blank. Right?

**Comment by cmgiven** [comment] 2015-04-06 18:32
I agree.

**Comment by gwenrr** [comment] 2015-04-06 18:33
Should also be same with LEA page. This LEA and DC

![screenshot 2015-04-06 14 32 58](https://cloud.githubusercontent.com/assets/7264714/7009673/e582b0ba-dc69-11e4-99b1-3f7f39218150.png)

**Comment by mepps** [comment] 2015-04-06 18:38
Good point @gwenrr. Just to note, this logic is trickier so it will take development time to make the adjustment. Let's discuss at 3.

**Comment by benjaminrobinson** [comment] 2015-04-06 18:39
@mepps:  Might it be easier with the data structure change we discussed in #127?  For sure a part of the discussion today...

**Comment by cmgiven** [comment] 2015-04-06 19:50
Per our call, the remaining piece here is to add logic to differentiate a school, LEA and state report card, add labels to the column "This School", "This LEA", and "DC" as appropriate, and remove the duplicate state column from that report card per #132.

**Comment by mepps** [comment] 2015-04-07 17:06
![screen shot 2015-04-07 at 1 06 07 pm](https://cloud.githubusercontent.com/assets/4406809/7028866/e7b21340-dd26-11e4-8314-9189d454f1fb.png)

This has been fixed on staging!

**Comment by cmgiven** [comment] 2015-04-07 17:18
Confirmed. Thanks, Maggie.

**Closed by cmgiven** 2015-04-07 17:18 UTC
