### ISSUE TITLE
School 188 shouldn't have dc cas data

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#66] opened 2015-01-08 19:42 UTC

**Comment by cmgiven** [comment] 2015-01-08 21:03
@benjaminrobinson: this is an issue that Gwen has the details on. This school code has been split, and the CAS data should follow the other school as this one is now early childhood only.

**Comment by benjaminrobinson** [comment] 2015-01-09 17:19
I see the issue...I think its a matter of the school mapping tables we use so I'll start looking into the issue there.

**Comment by benjaminrobinson** [comment] 2015-01-12 16:13
I will probably require your assistance on this @cmgiven as how to resolve this school code split issue is a little unclear to me.  This also relates to a separate issue to the school split surrounding Friendship.

**Comment by cmgiven** [comment] 2015-01-12 16:17
Okay. We'll add to the agenda for this afternoon.

**Comment by benjaminrobinson** [comment] 2015-01-12 16:19
We've been hit with a last minute data request from the mayor's office so I fear that I won't be able to get as much of this work done before our meeting.  So there's that...Just keeping you all in the loop!

**Comment by benjaminrobinson** [comment] 2015-01-13 16:11
Added to .gitignore file.  Will eventually appear here:  https://github.com/DC-OSSE/LearnDC_v2/blob/master/.gitignore

**Comment by benjaminrobinson** [comment] 2015-01-13 17:51
This is also the same for MGP, right?

**Comment by gwenrr** [comment] 2015-01-13 17:59
Yes - please hide MGP as well

**Comment by gwenrr** [comment] 2015-01-13 17:59
Thanks for catching this

**Comment by benjaminrobinson** [comment] 2015-01-13 18:00
Just going to add that file line to the .gitignore file as well...

**Comment by cmgiven** [comment] 2015-01-16 20:25
Ben, the file is still around. Please run the following command from the root directory of the repo and commit.

```git rm Export/JSON/school/0188/dccas.json Export/JSON/school/0188/mgp_scores.json```

**Comment by cmgiven** [comment] 2015-01-16 20:29
I should note that we will remove this by hand for the purposes of the pending push.

**Comment by benjaminrobinson** [comment] 2015-01-16 20:59
Weird...as I included that in the .gitignore file.  Why did that no do the trick?  I run this when in the context of the whole commit and push process?

**Comment by cmgiven** [comment] 2015-01-16 21:01
It ignored the file, but that just left it alone, it didn't delete it.

You can run that at any time before a commit and push. It'll delete the files and stage that deletion.

**Comment by benjaminrobinson** [comment] 2015-01-16 21:02
Thanks!  Good stuff to know for the future.

**Comment by gwenrr** [comment] 2015-01-16 22:50
This problem still exists.

**Comment by cmgiven** [comment] 2015-01-16 23:12
Sorry about that, Gwen. Check now (you may have to refresh). The exhibits are now gone.

**Comment by benjaminrobinson** [comment] 2015-01-16 23:16
I have not made a new commit to the repo...am trying to fix #85 before the push.  Or would you rather I push what I have now and work on fixing that issue at a later time?

**Comment by cmgiven** [comment] 2015-01-16 23:16
No urgency here. We fixed on our end. Just need to make sure those files are deleted before your next push with the ACGR fix.

**Comment by benjaminrobinson** [comment] 2015-01-16 23:20
Thanks, Chris!  I feel better knowing that I wasn't holding up anything on your or Maggie's end...

**Comment by benjaminrobinson** [comment] 2015-01-17 01:20
ACGR fix has been committed and pushed...but I'm still trying to resolve #85 and my re-running of Alex's old aggregator script (trying to see if the appeal  isn't being productive/responsive at the moment...will probably come back to it next week since this file is literally taking forever to finish.

**Closed by benjaminrobinson** 2015-01-17 01:20 UTC

**Comment by benjaminrobinson** [comment] 2015-01-20 16:34
@cmgiven Do I need to re-run that "git rm" command every time I make a commit/push from now on...especially since I am using the "git add --all" command?

**Comment by cmgiven** [comment] 2015-01-20 16:36
No, you're set. The issue is that the file was ignored before it was deleted from the repo. Thus the subsequent deletion had no effect. Creating the file again now won't affect anything, because the file remains ignored.

**Comment by benjaminrobinson** [comment] 2015-01-20 16:38
Good to know!  Thank you, Chris!
