### ISSUE TITLE
N<10 suppression, attendance and discipline

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#73] opened 2015-01-08 21:05 UTC
Each exhibit (attendance and discipline) need to have language added around subgroups with <10 students are not shown. I know Chris said this was there when we were meeting today, but I don't see it. It could be me :>)

**Comment by cmgiven** [comment] 2015-01-08 21:08
Duplicate of #68. Adding attendance note there.

**Closed by cmgiven** 2015-01-08 21:08 UTC
Labels: duplicate
